### ISSUE TITLE
unable to enroll more than one phrase to a profile

### ISSUE THREAD

**Issue by cthrash** [Microsoft/Cognitive-SpeakerRecognition-Windows#4]
https://github.com/Microsoft/Cognitive-Common-Windows/issues/4 moved here on behalf of @prateek03jan

**Comment by momohs** [comment]
@prateek03jan

According to the [documentation](https://www.microsoft.com/cognitive-services/en-us/speaker-recognition-api/documentation) of the speaker verification service, each speaker has to choose a specified phrase. A single profile cannot enroll using two different phrases at the same time. The speaker has to enroll using three recordings of the same phrase.

On the other hand, the speaker identification service does not have any restrictions on the spoken phrase.

Please let me know if you have any further questions.

**Comment by momohs** [comment]
I'll close this issue for now, please feel free to re-open if you have any further questions.
