### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by javenosa** [Microsoft/Cognitive-SpeakerRecognition-Windows#7]
Hello,

When the api will support spanish (Latinoamerica, Mexico, Argentina, etc)?

Thanks

**Comment by M-Sherif** [comment]
We would like to expand our languages coverage, but we don’t have concrete plans for supporting Spanish yet.
You can still use the text-independent speaker identification service for any language, but please note that “en-US and “zh-CN” are the official locales that we support. This means that you can use the locale “en-US” for sending Spanish audios, but we didn’t test and benchmark this scenario.
