### ISSUE TITLE
SampleUserControlLibrary doesn't exist, SPIDVerificationAPI_WPF_Sample doesn't build

### ISSUE THREAD

**Issue by gunnicus** [Microsoft/Cognitive-SpeakerRecognition-Windows#9]
Hi,
I was trying to run SPIDVerificationAPI_WPF_Sample.sln from VisualStudio, and here is the error I got, it show me SampleUserControlLibrary doesn't exist, I couldn't find this SampleUserControlLibrary anywhere:
![image](https://user-images.githubusercontent.com/4023477/35371557-ecfde240-01e8-11e8-8e45-3ca6d5eef5e9.png)

**Comment by gunnicus** [comment]
Ok, if I use Git it worked, for some reason the SampleUserControlLibrary is not in the .zip file, if I download the master package and unzip the SampleUserControlLibrary is missing.

**Comment by momohs** [comment]
The SampleUserControlLibrary is a git submodule. Apparently, GitHub does not include submodules when downloading projects as a *.zip file. The best way to download the code is using 
`git clone --recursive https://github.com/Microsoft/Cognitive-SpeakerRecognition-Windows.git`

I'll close this issue for now. Please feel free to re-open if you have any further questions.

**Comment by cthrash** [comment]
FYI, you can the SampleUserControlLibrary in .zip form [here](https://github.com/Microsoft/Cognitive-Common-Windows/archive/master.zip).

**Comment by gunnicus** [comment]
Thanks for your reply, 

Not sure why it has to be a submodule.

To be honest this is the first time I seen a "submodule". Usually for a github project I just download and unzip and it works.

Can't we make it easier for a newbie like me?
